### ISSUE TITLE
One shot events

### ISSUE THREAD

**Issue by hffmnn** [alinemorelli/react-gtm#113]
Hi,

I'd like to trigger one-shot events, e.g. when an error happened. But I don't want to persist the error details in the data layer. When doing something like this

```js
// some error occurred
TagManager.dataLayer({
    dataLayer: {
    category: "error",
    event: "errorEvent",
    errorId: "er-1234"
  }
});
// somewhere else in the code
TagManager.dataLayer({
    dataLayer: {
    category: "auth",
    event: "loginEvent",
  }
});
```

the `errorId` from the first call still gets send to `TagManager`. Is there an API I missed?

**Comment by joaopedromatias** [comment]
@hffmnn it happens due to the fact that Google Tag Manager **searches all over the dataLayer** in order to find the variable name (in this case, `errorId`). So it will persist for the next events even if that specific push does not have this variable on the object.

The way to solve this is by creating a function that automatically will reset all your variables, like this: 

```javascript
TagManager.dataLayer({
    dataLayer: {
    category: null,
    event: null,
    errorId: null
  }
});
```

**Comment by hffmnn** [comment]
Ah, ok. Thanks a lot!
