### ISSUE TITLE
Weird network requests

### ISSUE THREAD

**Issue by tincho** [alinemorelli/react-gtm#44]
Hi there!

after initializing `react-gtm` and send some events with `TagManager.dataLayer({...eventData})` I see my browser blocking/failing on some requests to ... Linkedin?

![image (3)](https://user-images.githubusercontent.com/178681/67341613-831f8280-f506-11e9-9db9-37b2f00b6346.png)

**Comment by lordenzo** [comment]
@tincho Can you confirm that you are not inserting any script that sends data to LinkedIn from your Google Tag Manager dashboard?
This component doesn't fire anything, so most likely, some scripts are being inserted by your GTM and theses might be the ones failing.

**Comment by tincho** [comment]
🤔  well, maybe... 
I don't have access to GTM dashboard, only the trackId, so I added the integration and saw that kind of suspicious. 
Didn't know it works this way, anyway. Thanks for the fast reply!

**Comment by lordenzo** [comment]
@tincho You should check with the people in charge of the GTM workspace you added, just to verify this.
Also, keep in mind that, the GTM workspace might add scripts to your page, that will be triggered when you push certain data or trigger events from your GTM. If any of those scripts has unhandled errors, code in your app might break and not be executed due to that script.

**Comment by alinemorelli** [comment]
@lordenzo is correct. The package does not trigger any calls, this is probably being triggered in the gtm itself.

As it is not a problem with this package I'm closing this issue.
